/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 desk.glb -T -p 6 -k
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/desk-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh name="Leg" geometry={nodes.Leg.geometry} material={materials["Material.007"]} position={[0.849183, 0.40161, -2.598419]} />
      <mesh name="Leg2" geometry={nodes.Leg2.geometry} material={materials["Material.007"]} position={[2.850663, 0.40161, -2.598419]} />
      <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials["Material.019"]} position={[1.749226, 0.802143, -2.564888]} />
    </group>
  );
}

useGLTF.preload("/desk-transformed.glb");
