/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 screen.glb -T -p 6
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/screen-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Screen.geometry} material={materials.Floor} position={[0.021955, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/screen-transformed.glb')
