/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 SimpleRoom.glb -T -p 6 -k
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SimpleRoom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Walls" geometry={nodes.Walls.geometry} material={materials['Material.015']} />
      <mesh name="Window" geometry={nodes.Window.geometry} material={materials['Material.015']} />
      <mesh name="WindowGlass" geometry={nodes.WindowGlass.geometry} material={materials.Glass} />
      <mesh name="Floor" geometry={nodes.Floor.geometry} material={materials['Material.015']} />
      <mesh name="Ceiling" geometry={nodes.Ceiling.geometry} material={materials['Material.015']} />
    </group>
  )
}

useGLTF.preload('/SimpleRoom-transformed.glb')
