/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 desk.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBakes } from "../hooks/useBakes";
import { MeshBasicMaterial, MeshStandardMaterial } from "three";

export function Desk(props) {
  const { nodes, materials } = useGLTF("/models/desk-transformed.glb");
  const bakeDesk = useBakes("desk");
  console.log(bakeDesk);
  const deskMaterial = new MeshStandardMaterial();

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Leg.geometry} material={materials["Material.007"]} position={[0.849183, 0.40161, -2.598419]} />
      <mesh geometry={nodes.Leg2.geometry} material={materials["Material.007"]} position={[2.850663, 0.40161, -2.598419]} />
      <mesh geometry={nodes.Plane016.geometry} material={deskMaterial} position={[1.749226, 0.802143, -2.564888]} />
    </group>
  );
}

useGLTF.preload("/models/desk-transformed.glb");
