/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dogs.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dogs(props) {
  const { nodes, materials } = useGLTF("/models/dogs-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Decoration_Toys_Minimal_Dogs_01.geometry}
        material={materials["Material.006"]}
        position={[-2.749541, 0.685919, 2.045165]}
        rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/models/dogs-transformed.glb");
