/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 knot.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Knot(props) {
  const { nodes, materials } = useGLTF("/models/knot-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Furniture_Detail_Cushion_Knot_01.geometry}
        material={materials.Fabric_Soft_White_Beige}
        position={[-0.293154, 0.509543, 2.266195]}
      />
    </group>
  );
}

useGLTF.preload("/models/knot-transformed.glb");
