/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 screen.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";

export function MovieScreen(props) {
  const { nodes, materials } = useGLTF("/models/screen-transformed.glb");
  const texture = useVideoTexture("/yourName.mp4", { muted: false, start: false });

  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Screen.geometry}
        position={[0.021955, 0, 0]}
      >
        <meshBasicMaterial
          map={texture}
          transparent={true}
          opacity={0.3}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/screen-transformed.glb");
