/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 photo.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Photo(props) {
  const { nodes, materials } = useGLTF("/models/photo-transformed.glb");
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials["Material.003"]}
        position={[-0.233865, 1.907814, 2.96552]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials["Material.010"]}
        position={[-1.233865, 1.907814, 2.96552]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials["Material.011"]}
        position={[-2.233865, 1.907814, 2.96552]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/photo-transformed.glb");
