/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 remote.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useDecoration } from "../hooks/useDecoration";

export function Remote(props) {
  const { nodes, materials } = useGLTF("/models/remote-transformed.glb");
  const toggle = useDecoration("toggleRemote");

  const handleClick = (e) => {
    e.stopPropagation();
    console.log("hello");
    toggle();
  };

  return (
    <group {...props} dispose={null} onClick={handleClick} name="remote">
      <group position={[0.491872, 1.473934, 0.649864]} rotation={[0, Math.PI / 6, 0]} scale={0.005975} name="remote">
        <mesh
          geometry={nodes.polySurface5.geometry}
          material={materials["Material.013"]}
          position={[-1.756506, 0.542251, -3.647138]}
          scale={0.647922}
          name="remote"
        />
      </group>
      <group position={[0.491872, 1.473934, 0.649864]} rotation={[0, Math.PI / 6, 0]} scale={0.005975} name="remote">
        <mesh geometry={nodes.polySurface7.geometry} material={materials["Material.013"]} position={[0, 0.000014, 0.000014]} name="remote" />
        <mesh geometry={nodes.polySurface8.geometry} material={materials["Material.013"]} position={[0, 0.000014, 0.000014]} name="remote" />
      </group>
      <mesh
        geometry={nodes.pCylinder20.geometry}
        material={materials["Material.012"]}
        position={[0.491872, 1.473934, 0.649864]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.005975}
        name="remote"
      />
      <mesh
        geometry={nodes.pPipe1.geometry}
        material={materials["Material.012"]}
        position={[0.4351, 1.470366, 0.61117]}
        rotation={[Math.PI / 2, 0, -Math.PI / 6]}
        scale={[0.024203, 0.024203, 0.007236]}
        name="remote"
      />
    </group>
  );
}

useGLTF.preload("/models/remote-transformed.glb");
