/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useProgress, useTexture } from "@react-three/drei";
import { Color, DoubleSide, MeshBasicMaterial, MeshPhysicalMaterial, MeshStandardMaterial, RepeatWrapping, Vector2, sRGBEncoding } from "three";
import { useSpring, animated } from "@react-spring/three";

export default function Room({ ...props }) {
  const { nodes, materials } = useGLTF("/models/room-transformed.glb");

  const group = useRef();
  const innerWalls = useRef();
  const outerWalls = useRef();
  const ceiling = useRef();
  const floor = useRef();
  const woodPath = useRef();
  const gardenFloor = useRef();

  const [start, setStart] = useState(false);
  const { scale } = useSpring({ scale: start ? 1 : 0 });

  useEffect(() => {
    innerWalls.current.geometry.attributes.uv2 = innerWalls.current.geometry.attributes.uv;
    outerWalls.current.geometry.attributes.uv2 = outerWalls.current.geometry.attributes.uv;
    ceiling.current.geometry.attributes.uv2 = ceiling.current.geometry.attributes.uv;
    floor.current.geometry.attributes.uv2 = floor.current.geometry.attributes.uv;
    floor.current.geometry.attributes.uv3 = floor.current.geometry.attributes.uv;
    woodPath.current.geometry.attributes.uv2 = woodPath.current.geometry.attributes.uv;
    gardenFloor.current.geometry.attributes.uv2 = gardenFloor.current.geometry.attributes.uv;
    setStart(true);
  }, []);

  //OUTERWALLS
  const colorOuter = useTexture("/textures/walls/material/color.jpg");
  colorOuter.repeat.set(15, 15);
  colorOuter.flipY = false;
  colorOuter.wrapS = RepeatWrapping;
  colorOuter.wrapT = RepeatWrapping;

  const roughnessOuter = useTexture("/textures/walls/material/roughness.jpg");
  roughnessOuter.repeat.set(15, 15);
  roughnessOuter.flipY = false;
  roughnessOuter.wrapS = RepeatWrapping;
  roughnessOuter.wrapT = RepeatWrapping;

  const normalOuter = useTexture("/textures/walls/material/normal.jpg");
  normalOuter.repeat.set(15, 15);
  normalOuter.flipY = false;
  normalOuter.wrapS = RepeatWrapping;
  normalOuter.wrapT = RepeatWrapping;

  const aoOuter = useTexture("/textures/walls/material/ao.jpg");
  aoOuter.repeat.set(15, 15);
  aoOuter.flipY = false;
  aoOuter.wrapS = RepeatWrapping;
  aoOuter.wrapT = RepeatWrapping;

  const outerWallsMaterial = new MeshStandardMaterial();
  outerWallsMaterial.map = colorOuter;
  outerWallsMaterial.normalMap = normalOuter;
  outerWallsMaterial.normalScale = new Vector2(5, 5);
  outerWallsMaterial.roughnessMap = roughnessOuter;
  outerWallsMaterial.aoMap = aoOuter;
  outerWallsMaterial.aoMapIntensity = 0.5;

  //CEILING
  const lightmapCeiling = useTexture("/textures/ceiling/bakes/LM.jpg");
  lightmapCeiling.encoding = sRGBEncoding;
  lightmapCeiling.flipY = false;

  const ceilingMaterial = new MeshStandardMaterial();
  ceilingMaterial.lightMap = lightmapCeiling;
  ceilingMaterial.lightMapIntensity = 50;
  ceilingMaterial.envMapIntensity = 0;

  //INNERWALS
  const lightMapWalls = useTexture("/textures/walls/bakes/LM.jpg");
  lightMapWalls.encoding = sRGBEncoding;
  lightMapWalls.flipY = false;

  const innerWallsMaterial = new MeshStandardMaterial();
  innerWallsMaterial.lightMap = lightMapWalls;
  innerWallsMaterial.lightMapIntensity = 50;
  innerWallsMaterial.envMapIntensity = 0;

  //FLOOR
  const color = useTexture("/textures/floor/material/color.jpg");
  color.repeat.set(6, 6);
  color.encoding = sRGBEncoding;
  color.flipY = false;
  color.wrapS = RepeatWrapping;
  color.wrapT = RepeatWrapping;

  const combined = useTexture("/textures/floor/bakes/combined.jpg");
  combined.encoding = sRGBEncoding;
  combined.flipY = false;

  const ao = useTexture("/textures/floor/material/ao.jpg");
  ao.repeat.set(6, 6);
  ao.encoding = sRGBEncoding;
  ao.flipY = false;
  ao.wrapS = RepeatWrapping;
  ao.wrapT = RepeatWrapping;

  const normal = useTexture("/textures/floor/material/normal.jpg");
  normal.repeat.set(6, 6);
  normal.encoding = sRGBEncoding;
  normal.flipY = false;
  normal.wrapS = RepeatWrapping;
  normal.wrapT = RepeatWrapping;

  const roughness = useTexture("/textures/floor/material/roughness.jpg");
  roughness.repeat.set(6, 6);
  roughness.encoding = sRGBEncoding;
  roughness.flipY = false;
  roughness.wrapS = RepeatWrapping;
  roughness.wrapT = RepeatWrapping;

  const lightMap = useTexture("/textures/floor/bakes/LM.jpg");
  lightMap.encoding = sRGBEncoding;
  lightMap.flipY = false;

  const floorMaterial = new MeshStandardMaterial();
  floorMaterial.envMapIntensity = 0;
  floorMaterial.map = color;
  floorMaterial.normalMap = normal;
  floorMaterial.normalScale = new Vector2(5, 5);
  floorMaterial.lightMap = lightMap;
  // floorMaterial.aoMap = ao;
  floorMaterial.roughnessMap = roughness;
  floorMaterial.lightMapIntensity = 15;

  //WINDOW
  const lightMapWindow = useTexture("/textures/windows/bakes/LM.jpg");
  lightMapWindow.encoding = sRGBEncoding;
  lightMapWindow.flipY = false;

  const windowFrameMaterial = materials.Windowframe;
  windowFrameMaterial.side = DoubleSide;
  // windowFrameMaterial.lightMap = lightMapWindow;
  // windowFrameMaterial.lightMapIntensity = 1;

  const windowGlassMaterial = new MeshPhysicalMaterial({
    metalness: 0,
    roughness: 0,
    envMapIntensity: 1,
    transparent: true,
    transmission: 1,
    opacity: 0.5,
  });

  //GARDEN
  const colorGarden = useTexture("/textures/garden/material/color.jpg");
  colorGarden.repeat.set(0.65, 0.5);
  // colorGarden.encoding = sRGBEncoding;
  colorGarden.flipY = false;
  colorGarden.wrapS = RepeatWrapping;
  colorGarden.wrapT = RepeatWrapping;

  const aoGarden = useTexture("/textures/garden/material/ao.jpg");
  // colorGarden.encoding = sRGBEncoding;
  aoGarden.repeat.set(0.65, 0.5);
  aoGarden.flipY = false;
  aoGarden.wrapS = RepeatWrapping;
  aoGarden.wrapT = RepeatWrapping;

  const normalGarden = useTexture("/textures/garden/material/normal.jpg");
  // normalGarden.encoding = sRGBEncoding;
  normalGarden.repeat.set(0.65, 0.5);
  normalGarden.flipY = false;
  normalGarden.wrapS = RepeatWrapping;
  normalGarden.wrapT = RepeatWrapping;

  const roughnessGarden = useTexture("/textures/garden/material/roughness.jpg");
  // roughnessGarden.encoding = sRGBEncoding;
  roughnessGarden.repeat.set(0.65, 0.5);
  roughnessGarden.flipY = false;
  roughnessGarden.wrapS = RepeatWrapping;
  roughnessGarden.wrapT = RepeatWrapping;

  const gardenMaterial = new MeshStandardMaterial();
  gardenMaterial.map = colorGarden;
  gardenMaterial.normalMap = normalGarden;
  gardenMaterial.normalScale = new Vector2(4, 4);
  gardenMaterial.aoMap = aoGarden;
  gardenMaterial.aoMapIntensity = 1;
  gardenMaterial.roughnessMap = roughnessGarden;
  // gardenMaterial.roughness = 1.1;
  gardenMaterial.envMapIntensity = 1.5;

  //WOODPATH
  const colorWood = useTexture("/textures/woodPath/material/color.jpg");
  colorWood.repeat.set(6, 6);
  colorWood.encoding = sRGBEncoding;
  colorWood.flipY = false;
  colorWood.wrapS = RepeatWrapping;
  colorWood.wrapT = RepeatWrapping;

  const aoWood = useTexture("/textures/woodPath/material/ao2.jpg");
  // aoWood.encoding = sRGBEncoding;
  // aoWood.repeat.set(6, 6);
  aoWood.flipY = false;
  // aoWood.wrapS = RepeatWrapping;
  // aoWood.wrapT = RepeatWrapping;

  const normalWood = useTexture("/textures/woodPath/material/normal.jpg");
  // normalGarden.encoding = sRGBEncoding;
  normalWood.repeat.set(6, 6);
  normalWood.flipY = false;
  normalWood.wrapS = RepeatWrapping;
  normalWood.wrapT = RepeatWrapping;

  const roughnessWood = useTexture("/textures/woodPath/material/roughness.jpg");
  // roughnessGarden.encoding = sRGBEncoding;
  roughnessWood.repeat.set(6, 6);
  roughnessWood.flipY = false;
  roughnessWood.wrapS = RepeatWrapping;
  roughnessWood.wrapT = RepeatWrapping;

  const woodpathMaterial = new MeshStandardMaterial();
  woodpathMaterial.map = colorWood;
  woodpathMaterial.normalMap = normalWood;
  woodpathMaterial.normalScale = new Vector2(5, 5);
  woodpathMaterial.aoMap = aoWood;
  woodpathMaterial.aoMapIntensity = 1;
  woodpathMaterial.envMapIntensity = 2.5;

  return (
    <animated.group ref={group} {...props} dispose={null} scale={scale}>
      <mesh geometry={nodes.Base.geometry} material={materials["Material.002"]} position={[0, -0.003441, 0]} />
      <mesh ref={floor} geometry={nodes.Floor.geometry} material={floorMaterial} position={[0, -0.003441, 0]} />
      <mesh ref={ceiling} geometry={nodes.Ceiling.geometry} material={ceilingMaterial} position={[0, 2.956559, 0]} />
      <mesh ref={outerWalls} geometry={nodes.OuterWalls.geometry} material={outerWallsMaterial} position={[-2.9, 1.595, 0]} />
      <mesh ref={innerWalls} geometry={nodes.InnerWalls.geometry} material={innerWallsMaterial} position={[3, 1.111622, 0.965227]} />
      <mesh geometry={nodes.Window.geometry} material={windowFrameMaterial} position={[-2.9, 1.6, 0]} />
      <mesh geometry={nodes.WindowGlass.geometry} material={windowGlassMaterial} position={[-2.9, 1.6, 0]} />
      <mesh ref={gardenFloor} geometry={nodes.GardenFloor.geometry} material={gardenMaterial} position={[3, 0, 6]} />
      <mesh ref={woodPath} geometry={nodes.WoodPath.geometry} material={woodpathMaterial} position={[0, -0.003441, 0]} />
      <mesh geometry={nodes.Pilar.geometry} material={materials["Material.004"]} position={[8.75, 1.1, 3.75]} />
      <mesh geometry={nodes.OutdoorCeiling.geometry} material={materials["Material.006"]} position={[0, 2.996559, 0]} />
    </animated.group>
  );
}

useGLTF.preload("/models/room-transformed.glb");
