/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sofa.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Sofa(props) {
  const { nodes, materials } = useGLTF("/models/sofa-transformed.glb");
  return (
    <group
      position={[-0.18177, 0, 1.748561]}
      rotation={[0, -1.570535, 0]}
    >
      <mesh
        geometry={nodes.Thick_Piping_Sofa_1.geometry}
        material={materials["Coloured Fabric.005"]}
      />
      <mesh
        geometry={nodes.Thick_Piping_Sofa_2.geometry}
        material={materials["Plastic Gloss Black"]}
      />
    </group>
  );
}

useGLTF.preload("/models/sofa-transformed.glb");
