/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tvShelve.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TvShelve(props) {
  const { nodes, materials } = useGLTF("/models/tvShelve-transformed.glb");
  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        position={[-2.976637, 0.333676, 2.627388]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      >
        <mesh
          geometry={nodes["uploads_files_4201386_tv+stand_1"].geometry}
          material={materials.Wood_Bamboo}
        />
        <mesh
          geometry={nodes["uploads_files_4201386_tv+stand_2"].geometry}
          material={materials.Color_M01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/tvShelve-transformed.glb");
